### ISSUE TITLE
Question about the outpus of mpiBWA and mpiBWAByChr

### ISSUE THREAD

**Issue by phupe** [bioinfo-pf-curie/mpiBWA#15]
When I launch `mpiBWA` using `bash standard.sh` from the `example` I get in the only one sam file which is `HCC1187C.sam`.

When I launch `mpiBWAByChr` by replacing `mpiBWA` by `mpiBWAByChr` in the file `standard.sh` , I get more files:

- chr1.sam
- HCC1187C.sam
- unmapped.sam
- discordant.sam

Is it the expected behaviour?

In the case of  `mpiBWA`, are the unmapped and discordant reads in the HCC1187C.sam file?

**Comment by phupe** [comment]
OK. got it, my questions have been answered in the new doc.

**Comment by fredjarlier** [comment]
Yes this is expected. 

HCC118C contains only the header of the reference genome with the @SQ lines.

The name chr1.sam comes from the @SQ lines. 

So far the chimeric alignment are separated in a discordant.sam. 

The purpose of mpiBWAByChr is to split the output SAM by chromosome.
And this in order to facilitate the sorting. This way each chromosome can be sorted independantly and in parallel with mpiSort. It will take much less memory and cpu than sorting the whole SAM.

**Comment by fredjarlier** [comment]
We could discuss the name of the output files this is confusing some times.
